/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ApiConfiguration.gltf -o src/components/ApiConfiguration.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ApiConfiguration(props) {
  const { nodes, materials } = useGLTF('/models/ApiConfiguration.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['a2.002']} position={[-1.052, -0.664, 0.385]} rotation={[-1.546, 0.359, -0.323]} scale={5.561} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['a2.002']} position={[0.378, 0.128, 0.164]} rotation={[1.49, -0.024, 0.295]} scale={[2.83, 2.701, 2.83]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.001']} position={[0.394, 0.123, 0.111]} rotation={[-1.658, 0.018, -0.302]} scale={9.538} />
      <mesh geometry={nodes.Text.geometry} material={materials['a2.006']} position={[0.282, 0.156, 0.468]} rotation={[1.488, -0.026, 0.303]} scale={0.901} />
    </group>
  )
}

useGLTF.preload('/models/ApiConfiguration.gltf')
