/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/guitarman.gltf -o src/components/GuitarMan.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GuitarMan(props) {
  const { nodes, materials } = useGLTF('/models/guitarman.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.red} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.grey} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.grey} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.silver} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Skin} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_12.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.mesh_12_1.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.006']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Skin} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_15.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.mesh_15_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.mesh_15_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.mesh_15_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.mesh_15_4.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.silver} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.silver} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.silver} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.silver} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.NurbsPath.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.NurbsPath001.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.NurbsPath002.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.NurbsPath003.geometry} material={materials.black} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.white} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.009']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.009']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Torus001.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/guitarman.gltf')
