/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/NFTFrameArt.glb -o src/components/NFTFrameArt.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NFTFrameArt(props) {
  const { nodes, materials } = useGLTF('/models/NFTFrameArt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[1.043, 3.226, 0.157]} rotation={[-0.145, 0.373, 0.037]} scale={[2.305, 2.305, 0.363]} />
    </group>
  )
}

useGLTF.preload('/models/NFTFrameArt.glb')
