/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/NFTFrameArt.glb -o src/components/NFTFrameArt.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { TextureLoader } from 'three';

export function PictureFrame(props) {
  const { nodes, materials } = useGLTF('/models/PictureFrame.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube012.geometry} 
        material={materials['Material.001']} 
        position={[1.25, 3, -1]} 
        rotation={[0.35, -3, 0.1]} 
        scale={[2.305, 2.305, 0.363]} 
      />       
    </group>
  )
}

useGLTF.preload('/models/PictureFrame.glb')
