/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/UserLogin.gltf -o src/components/UserLogin.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function UserLogin(props) {
  const { nodes, materials } = useGLTF('/models/UserLogin.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere004.geometry} material={materials['a2.006']} position={[0.074, 0.995, -0.039]} rotation={[-0.189, -0.347, -0.239]} scale={0.172} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['a2.002']} position={[0.103, 0.98, -0.116]} rotation={[-0.189, -0.347, -0.239]} scale={0.867} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Material.001']} position={[-0.157, 0.14, 0.155]} rotation={[-0.189, -0.347, -0.239]} scale={0.953} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['a2.002']} position={[1.056, 0.465, 0.105]} rotation={[-0.194, -0.344, -0.241]} scale={1.133} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.001']} position={[-0.004, 0.162, -0.219]} rotation={[-0.191, -0.345, -0.24]} scale={32.856} />
      <mesh geometry={nodes.Cube064.geometry} material={materials['Material.001']} position={[-0.02, 0.17, -0.176]} rotation={[-0.191, -0.345, -0.24]} scale={[32.856, 32.856, 3.61]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-0.283, -0.414, 0.213]} rotation={[-0.189, -0.347, -0.239]} scale={0.953} />
      <mesh geometry={nodes.Cube160.geometry} material={materials['a2.002']} position={[0.116, -1.151, 0.521]} rotation={[-0.188, -0.342, -0.237]} scale={2.618} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['a2.006']} position={[0.078, -1.139, 0.553]} rotation={[-0.193, -0.342, -0.244]} scale={0.423} />
    </group>
  )
}

useGLTF.preload('/models/UserLogin.gltf')
