/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/WebConfiguration.gltf -o src/components/WebConfiguration.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WebConfiguration(props) {
  const { nodes, materials } = useGLTF('/models/WebConfiguration.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.105, -1.584, -1.262]} rotation={[0, -0.161, 0]} scale={[1.136, 1.351, 1.351]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[-0.153, 0.331, -1.004]} rotation={[0, -0.175, 0]} scale={2.135} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[-0.101, 0.279, -1.297]} rotation={[0, -0.175, 0]} scale={2.135} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['a2.002']} position={[1.239, 1.077, -0.207]} rotation={[-1.481, 0.485, -0.204]} scale={4.061} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} position={[0.301, 1.574, -0.26]} rotation={[-1.575, -0.007, -0.182]} scale={2.512} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['a2.002']} position={[-1.043, 0.966, -0.7]} rotation={[0.002, -0.175, 0]} scale={1.147} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['a2.006']} position={[-0.684, 0.383, -0.673]} rotation={[0.002, -0.175, -0.436]} scale={0.577} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['a2.006']} position={[-0.732, -0.109, -0.683]} rotation={[0.002, -0.175, -1.57]} scale={0.434} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.001']} position={[-0.214, 0.966, -0.614]} rotation={[0.002, -0.175, 0]} scale={1.205} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['a2.002']} position={[-0.202, 0.495, -0.743]} rotation={[0.002, -0.175, 0]} scale={1.15} />
    </group>
  )
}

useGLTF.preload('/models/WebConfiguration.gltf')
